# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-sprockets"
# gem "middleman-slim"
gem "slim", "~> 1.3.6"
gem "susy"
gem 'compass', '~>0.12.4'

gem "rack-reverse-proxy", :require => "rack/reverse_proxy"
